// generator/angular-generator/expressions/import-declaration.ts
import { ImportDeclaration as BaseImportDeclaration } from "../../base-generator/expressions/import";
import { Decorators } from "../../component_declaration/decorators";

export class ImportDeclaration extends BaseImportDeclaration {
  compileComponentDeclarationImport() {
    const imports: string[] = [];
    if (this.has("createContext")) {
      imports.push("Injectable");
    }
    if (this.has(Decorators.Consumer)) {
      imports.push("SkipSelf", "Host");
    }

    if (imports.length) {
      return `import { ${imports} } from "@angular/core"`;
    }

    return super.compileComponentDeclarationImport();
  }
}

// generator/react-generator/expressions/import-declaration.ts
import { ImportDeclaration as BaseImportDeclaration } from "../../base-generator/expressions/import";

export class ImportDeclaration extends BaseImportDeclaration {
  compileComponentDeclarationImport() {
    if (this.has("createContext")) {
      return `import { createContext } from "react"`;
    }
    return super.compileComponentDeclarationImport();
  }
}
