// projects/angular-app/src/app/DxButtonGroup.ts
import { Component, Input, Output, EventEmitter, ContentChild, ElementRef } from '@angular/core';
import { DxButtonComponent } from "./DxButton";

@Component({
  selector: 'dx-button-group',
  template: `
        <div class="dx-button-group">
            <dx-button
                class="item"
                *ngFor="let item of _viewModel.items; let i = index; trackBy: trackBy"
                (click)="onClickHandler(i)"
                [stylingMode]="_viewModel.stylingMode"
                [pressed]="item.pressed"
                [text]="item.text"
                [classNames]="item.classNames"
                [type]="item.type"
                [hint]="item.hint || _viewModel.hint"
                >
            </dx-button>
        </div>
    `,
  entryComponents: [DxButtonComponent],
  styleUrls: ["./dx-group-button.css"]
})
export class DxButtonGroupComponent {
  @Input() height: String;
  @Input() hint: String;
  @Input() items: Array<any> = [];
  @Input() keyExpr: string;
  @Input() selectionMode: String;
  @Input() stylingMode: String;
  @Input() width: String;

  _selectedItems: Array<String> = [];
  @Output() selectedItemsChange = new EventEmitter();
  @Input() get selectedItems() {
    return this._selectedItems;
  }
  set selectedItems(value) {
    this._selectedItems = value;
    this.selectedItemsChange.emit(value);
  }

  onClickHandler(index: number) {
    const currentButton = this.items[index][this.keyExpr];
    if (this.selectionMode === "single") {
      if (this.selectedItems[0] === currentButton) {
        this.selectedItems = [];
      } else {
        this.selectedItems = [currentButton];
      }
    } else {
      if (this.selectedItems.indexOf(currentButton) !== -1) {
        this.selectedItems = this.selectedItems.filter(item => item !== currentButton);
      } else {
        this.selectedItems = this.selectedItems.concat(currentButton);
      }
    }
  }

  trackBy(item) {
    return item[this.keyExpr];
  }

  viewModel(model) {
    const viewModel = Object.assign({}, model);
    viewModel.items = viewModel.items.map((item, i, array) => (Object.assign({}, item,
      {
        pressed: (model.selectedItems || []).indexOf(item[model.keyExpr]) !== -1,
        classNames: [i === 0 && "first" || (i === array.length - 1) && "last" || ""]
      }
    )));

    return viewModel;
  }

  getModel() {
    return {
      height: this.height,
      hint: this.hint,
      width: this.width,
      items: this.items,
      keyExpr: this.keyExpr,
      selectedItems: this.selectedItems,
      selectionMode: this.selectionMode,
      stylingMode: this.stylingMode
    };
  }

  _viewModel: any;
  ngDoCheck() {
    this._viewModel = this.viewModel(this.getModel());
  }
}

// projects/vue-app/src/components/DxButtonGroup.vue
<script>
import DxButton from "./DxButton";

export default {
  components: {
    DxButton
  },
  props: {
    height: String,
    hint: String,
    items: Array,
    keyExpr: String,
    selectionMode: String,
    stylingMode: String,
    width: String,
    selectedItems: Array
  },
  data() {
    return {
      // state: {
      //   selectedItems: this.$options.propsData.selectedItems
      // }
    };
  },
  // created() {
  //   Object.defineProperty(this, "s_selectedItems", {
  //     get: function() {
  //       return (this.$options.propsData.selectedItems !== undefined
  //         ? this.$options.propsData.selectedItems
  //         : this.state.selectedItems) || [];
  //     },
  //     set: function(selectedItems) {
  //       this.state.selectedItems = selectedItems;
  //       this.$emit("selected-items-change", selectedItems);
  //     }
  //   });
  // },
  methods: {
    onClickHandler(index) {
      const currentButton = this.items[index][this.keyExpr];
      if (this.selectionMode === "single") {
        if (this.selectedItems[0] === currentButton) {
          this.selectedItems = [];
        } else {
          this.selectedItems = [currentButton];
        }
      } else {
        if (this.selectedItems.indexOf(currentButton) !== -1) {
          this.selectedItems = this.selectedItems.filter(
            item => item !== currentButton
          );
        } else {
          this.selectedItems = this.selectedItems.concat(currentButton);
        }
      }
      this.$emit("selected-items-change", this.selectedItems);
    },

    viewModel(model) {
      const viewModel = { ...model };
      viewModel.items = viewModel.items.map(item => ({
        ...item,
        pressed: (model.selectedItems || []).indexOf(item[model.keyExpr]) !== -1
      }));

      return viewModel;
    },

    view(viewModel) {
      const buttons = viewModel.items.map((item, index) => (
        <DxButton
          key={item.key}
          pressed={item.pressed}
          stylingMode={viewModel.stylingMode}
          text={item.text}
          type={item.type}
          hint={item.hint || viewModel.hint}
          vOn:on-click={this.onClickHandler.bind(this, index)}
        />
      ));

      return <div class="dx-button-group">{buttons}</div>;
    },

    getModel() {
      return {
        height: this.height,
        hint: this.hint,
        stylingMode: this.stylingMode,
        width: this.width,
        items: this.items,
        keyExpr: this.keyExpr,
        selectionMode: this.selectionMode,
        selectedItems: this.selectedItems
      };
    }
  },
  render() {
    return this.view(this.viewModel(this.getModel()));
  }
};
</script>
<style>
.dx-button-group {
  display: inline-block;
}

.dx-button-group .dx-button-mode-outlined,
.dx-button-group .dx-button-mode-contained {
  border-radius: 0;
}

.dx-button-group .dx-button-mode-outlined,
.dx-button-group .dx-button-mode-contained {
  padding-left: 1px;
  padding-right: 1px;
  border-left-width: 0;
}

.dx-button-group .dx-button-mode-outlined:first-child,
.dx-button-group .dx-button-mode-contained:first-child,
.dx-button-group .dx-button-mode-outlined.dx-state-hover:first-child,
.dx-button-group .dx-button-mode-contained.dx-state-hover:first-child {
  border-top-left-radius: 4px;
  border-bottom-left-radius: 4px;
  padding-left: 0;
  border-left-width: 1px;
}

.dx-button-group .dx-button-mode-outlined:last-child,
.dx-button-group .dx-button-mode-contained:last-child,
.dx-button-group .dx-button-mode-outlined.dx-state-hover:last-child,
.dx-button-group .dx-button-mode-contained.dx-state-hover:last-child {
  border-top-right-radius: 4px;
  border-bottom-right-radius: 4px;
}
</style>
