// projects/angular-app/src/app/DxDrawer.ts
import { Component, EventEmitter, Input, NgModule, Output, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'dx-drawer',
  template: `<div
    class="dx-drawer"
    [title]="hint"
    [ngStyle]="style">
    <div [class]="drawerCSS">
      <ng-content select="[drawer]"></ng-content>
    </div>
    <div
      class="dx-drawer-content"
      (click)="onClickHandler($event)">
        <ng-content></ng-content>
    </div>
  </div>`,
  styleUrls: ['./dx-drawer.css'],
  encapsulation: ViewEncapsulation.ShadowDom
})

export class DxDrawerComponent {
  @Input() height?: string;
  @Input() hint?: string;
  @Input() width?: string;

  @Input() opened: boolean;
  @Output() openedChange = new EventEmitter();

  onClickHandler(e) {
    this.opened = false;
    this.openedChange.emit(this.opened);
  }

  get drawerCSS() {
    return ["dx-drawer-panel"].concat(this.opened ? "dx-state-visible" : "dx-state-hidden").join(" ");
  }

  get style() {
    return {
      width: this.width,
      height: this.height
    };
  }
}

@NgModule({
  declarations: [DxDrawerComponent],
  imports: [
    CommonModule
  ],
  exports: [DxDrawerComponent]
})
export class DxDrawerModule { }

// projects/vue-app/src/components/DxDrawer.vue
<script>
export default {
  components: {
  },
  props: {
    height: String,
    hint: String,
    opened: {
      type: Boolean,
      default: undefined
    },
    width: String
  },
  data() {
    return {
      opened_state: this.opened
    };
  },
  methods: {
    onClickHandler() {
      this.opened_state = false;
      this.$emit("opened-change", this.opened_state);
    },

    drawerCSS() {
      return ["dx-drawer-panel"]
        .concat((this.opened !== undefined ? this.opened : this.opened_state) ? "dx-state-visible" : "dx-state-hidden")
        .join(" ");
    },

    style() {
      return {
        width: this.width,
        height: this.height
      };
    },

    view(viewModel) {
      return (
        <div
          class="dx-drawer"
          title={viewModel.hint}
          style={viewModel.style()}>
          <div class={viewModel.drawerCSS()}>
            {
              viewModel.$scopedSlots.drawer()
            }
          </div>
          <div
            class="dx-drawer-content"
            on-click={viewModel.onClickHandler}>
            {
              viewModel.$scopedSlots.default()
            }
          </div>
        </div>
      );
    }
  },
  render() {
    return this.view(this);
  }
};
</script>
<style>
.dx-drawer {
  width: 100%;
  height: 100%;
  position: relative;
  overflow: hidden;
  overflow-y: visible;
}

.dx-drawer .dx-drawer-content {
  overflow: hidden;
  width: 100%;
  height: 100%;
  top: 0;
}

.dx-drawer .dx-drawer-panel {
  background-color: #337ab7;
  overflow: visible;
  position: absolute;
  top: 0;
  bottom: 0;
  width: 200px;
}

.dx-drawer .dx-drawer-panel.dx-state-visible {
  left: 0;
  transition: left 300ms;
}

.dx-drawer .dx-drawer-panel.dx-state-hidden {
  left: -200px;
  transition: left 300ms;
}
</style>
