// packages/react/src/expressions/import-declaration.ts
import { ImportDeclaration as BaseImportDeclaration } from "../../base-generator/expressions/import";

export class ImportDeclaration extends BaseImportDeclaration {
  compileComponentDeclarationImport() {
    const react: string[] = [];
    const reactDom: string[] = [];
    const result: string[] = [];
    if (this.has("createContext")) {
      react.push("createContext");
    }

    if (this.has("Portal")) {
      reactDom.push("createPortal");
    }

    if (react.length) {
      result.push(`import { ${react} } from "react"`);
    }
    if (reactDom.length) {
      result.push(`import { ${reactDom} } from "react-dom"`);
    }

    if (result.length) {
      return result.join("\n;");
    }

    return super.compileComponentDeclarationImport();
  }
}

// generator/angular-generator/expressions/import-declaration.ts
import { ImportDeclaration as BaseImportDeclaration } from "../../base-generator/expressions/import";
import { Decorators } from "../../component_declaration/decorators";

export class ImportDeclaration extends BaseImportDeclaration {
  compileComponentDeclarationImport() {
    const imports: string[] = [];
    if (this.has("createContext")) {
      imports.push("Injectable");
    }
    if (this.has(Decorators.Consumer)) {
      imports.push("SkipSelf", "Host");
    }

    if (imports.length) {
      return `import { ${imports} } from "@angular/core"`;
    }

    return super.compileComponentDeclarationImport();
  }
}
